/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SluzbyRouteImport } from './routes/sluzby'
import { Route as PodporujemeRouteImport } from './routes/podporujeme'
import { Route as OvereniDicRouteImport } from './routes/overeni-dic'
import { Route as OdkazyRouteImport } from './routes/odkazy'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as EnRouteImport } from './routes/en'
import { Route as CenikRouteImport } from './routes/cenik'
import { Route as BulletinRouteImport } from './routes/bulletin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EnIndexRouteImport } from './routes/en.index'
import { Route as BulletinIndexRouteImport } from './routes/bulletin.index'
import { Route as EnSluzbyRouteImport } from './routes/en.sluzby'
import { Route as EnPodporujemeRouteImport } from './routes/en.podporujeme'
import { Route as EnOvereniDicRouteImport } from './routes/en.overeni-dic'
import { Route as EnOdkazyRouteImport } from './routes/en.odkazy'
import { Route as EnKontaktRouteImport } from './routes/en.kontakt'
import { Route as EnCenikRouteImport } from './routes/en.cenik'
import { Route as EnBulletinRouteImport } from './routes/en.bulletin'
import { Route as BulletinIdRouteImport } from './routes/bulletin.$id'
import { Route as EnBulletinIndexRouteImport } from './routes/en.bulletin.index'
import { Route as EnBulletinIdRouteImport } from './routes/en.bulletin.$id'

const SluzbyRoute = SluzbyRouteImport.update({
  id: '/sluzby',
  path: '/sluzby',
  getParentRoute: () => rootRouteImport,
} as any)
const PodporujemeRoute = PodporujemeRouteImport.update({
  id: '/podporujeme',
  path: '/podporujeme',
  getParentRoute: () => rootRouteImport,
} as any)
const OvereniDicRoute = OvereniDicRouteImport.update({
  id: '/overeni-dic',
  path: '/overeni-dic',
  getParentRoute: () => rootRouteImport,
} as any)
const OdkazyRoute = OdkazyRouteImport.update({
  id: '/odkazy',
  path: '/odkazy',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const EnRoute = EnRouteImport.update({
  id: '/en',
  path: '/en',
  getParentRoute: () => rootRouteImport,
} as any)
const CenikRoute = CenikRouteImport.update({
  id: '/cenik',
  path: '/cenik',
  getParentRoute: () => rootRouteImport,
} as any)
const BulletinRoute = BulletinRouteImport.update({
  id: '/bulletin',
  path: '/bulletin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EnRoute,
} as any)
const BulletinIndexRoute = BulletinIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BulletinRoute,
} as any)
const EnSluzbyRoute = EnSluzbyRouteImport.update({
  id: '/sluzby',
  path: '/sluzby',
  getParentRoute: () => EnRoute,
} as any)
const EnPodporujemeRoute = EnPodporujemeRouteImport.update({
  id: '/podporujeme',
  path: '/podporujeme',
  getParentRoute: () => EnRoute,
} as any)
const EnOvereniDicRoute = EnOvereniDicRouteImport.update({
  id: '/overeni-dic',
  path: '/overeni-dic',
  getParentRoute: () => EnRoute,
} as any)
const EnOdkazyRoute = EnOdkazyRouteImport.update({
  id: '/odkazy',
  path: '/odkazy',
  getParentRoute: () => EnRoute,
} as any)
const EnKontaktRoute = EnKontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => EnRoute,
} as any)
const EnCenikRoute = EnCenikRouteImport.update({
  id: '/cenik',
  path: '/cenik',
  getParentRoute: () => EnRoute,
} as any)
const EnBulletinRoute = EnBulletinRouteImport.update({
  id: '/bulletin',
  path: '/bulletin',
  getParentRoute: () => EnRoute,
} as any)
const BulletinIdRoute = BulletinIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BulletinRoute,
} as any)
const EnBulletinIndexRoute = EnBulletinIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EnBulletinRoute,
} as any)
const EnBulletinIdRoute = EnBulletinIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EnBulletinRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bulletin': typeof BulletinRouteWithChildren
  '/cenik': typeof CenikRoute
  '/en': typeof EnRouteWithChildren
  '/kontakt': typeof KontaktRoute
  '/odkazy': typeof OdkazyRoute
  '/overeni-dic': typeof OvereniDicRoute
  '/podporujeme': typeof PodporujemeRoute
  '/sluzby': typeof SluzbyRoute
  '/bulletin/$id': typeof BulletinIdRoute
  '/en/bulletin': typeof EnBulletinRouteWithChildren
  '/en/cenik': typeof EnCenikRoute
  '/en/kontakt': typeof EnKontaktRoute
  '/en/odkazy': typeof EnOdkazyRoute
  '/en/overeni-dic': typeof EnOvereniDicRoute
  '/en/podporujeme': typeof EnPodporujemeRoute
  '/en/sluzby': typeof EnSluzbyRoute
  '/bulletin/': typeof BulletinIndexRoute
  '/en/': typeof EnIndexRoute
  '/en/bulletin/$id': typeof EnBulletinIdRoute
  '/en/bulletin/': typeof EnBulletinIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cenik': typeof CenikRoute
  '/kontakt': typeof KontaktRoute
  '/odkazy': typeof OdkazyRoute
  '/overeni-dic': typeof OvereniDicRoute
  '/podporujeme': typeof PodporujemeRoute
  '/sluzby': typeof SluzbyRoute
  '/bulletin/$id': typeof BulletinIdRoute
  '/en/cenik': typeof EnCenikRoute
  '/en/kontakt': typeof EnKontaktRoute
  '/en/odkazy': typeof EnOdkazyRoute
  '/en/overeni-dic': typeof EnOvereniDicRoute
  '/en/podporujeme': typeof EnPodporujemeRoute
  '/en/sluzby': typeof EnSluzbyRoute
  '/bulletin': typeof BulletinIndexRoute
  '/en': typeof EnIndexRoute
  '/en/bulletin/$id': typeof EnBulletinIdRoute
  '/en/bulletin': typeof EnBulletinIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bulletin': typeof BulletinRouteWithChildren
  '/cenik': typeof CenikRoute
  '/en': typeof EnRouteWithChildren
  '/kontakt': typeof KontaktRoute
  '/odkazy': typeof OdkazyRoute
  '/overeni-dic': typeof OvereniDicRoute
  '/podporujeme': typeof PodporujemeRoute
  '/sluzby': typeof SluzbyRoute
  '/bulletin/$id': typeof BulletinIdRoute
  '/en/bulletin': typeof EnBulletinRouteWithChildren
  '/en/cenik': typeof EnCenikRoute
  '/en/kontakt': typeof EnKontaktRoute
  '/en/odkazy': typeof EnOdkazyRoute
  '/en/overeni-dic': typeof EnOvereniDicRoute
  '/en/podporujeme': typeof EnPodporujemeRoute
  '/en/sluzby': typeof EnSluzbyRoute
  '/bulletin/': typeof BulletinIndexRoute
  '/en/': typeof EnIndexRoute
  '/en/bulletin/$id': typeof EnBulletinIdRoute
  '/en/bulletin/': typeof EnBulletinIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bulletin'
    | '/cenik'
    | '/en'
    | '/kontakt'
    | '/odkazy'
    | '/overeni-dic'
    | '/podporujeme'
    | '/sluzby'
    | '/bulletin/$id'
    | '/en/bulletin'
    | '/en/cenik'
    | '/en/kontakt'
    | '/en/odkazy'
    | '/en/overeni-dic'
    | '/en/podporujeme'
    | '/en/sluzby'
    | '/bulletin/'
    | '/en/'
    | '/en/bulletin/$id'
    | '/en/bulletin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cenik'
    | '/kontakt'
    | '/odkazy'
    | '/overeni-dic'
    | '/podporujeme'
    | '/sluzby'
    | '/bulletin/$id'
    | '/en/cenik'
    | '/en/kontakt'
    | '/en/odkazy'
    | '/en/overeni-dic'
    | '/en/podporujeme'
    | '/en/sluzby'
    | '/bulletin'
    | '/en'
    | '/en/bulletin/$id'
    | '/en/bulletin'
  id:
    | '__root__'
    | '/'
    | '/bulletin'
    | '/cenik'
    | '/en'
    | '/kontakt'
    | '/odkazy'
    | '/overeni-dic'
    | '/podporujeme'
    | '/sluzby'
    | '/bulletin/$id'
    | '/en/bulletin'
    | '/en/cenik'
    | '/en/kontakt'
    | '/en/odkazy'
    | '/en/overeni-dic'
    | '/en/podporujeme'
    | '/en/sluzby'
    | '/bulletin/'
    | '/en/'
    | '/en/bulletin/$id'
    | '/en/bulletin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BulletinRoute: typeof BulletinRouteWithChildren
  CenikRoute: typeof CenikRoute
  EnRoute: typeof EnRouteWithChildren
  KontaktRoute: typeof KontaktRoute
  OdkazyRoute: typeof OdkazyRoute
  OvereniDicRoute: typeof OvereniDicRoute
  PodporujemeRoute: typeof PodporujemeRoute
  SluzbyRoute: typeof SluzbyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sluzby': {
      id: '/sluzby'
      path: '/sluzby'
      fullPath: '/sluzby'
      preLoaderRoute: typeof SluzbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podporujeme': {
      id: '/podporujeme'
      path: '/podporujeme'
      fullPath: '/podporujeme'
      preLoaderRoute: typeof PodporujemeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overeni-dic': {
      id: '/overeni-dic'
      path: '/overeni-dic'
      fullPath: '/overeni-dic'
      preLoaderRoute: typeof OvereniDicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/odkazy': {
      id: '/odkazy'
      path: '/odkazy'
      fullPath: '/odkazy'
      preLoaderRoute: typeof OdkazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en': {
      id: '/en'
      path: '/en'
      fullPath: '/en'
      preLoaderRoute: typeof EnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cenik': {
      id: '/cenik'
      path: '/cenik'
      fullPath: '/cenik'
      preLoaderRoute: typeof CenikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulletin': {
      id: '/bulletin'
      path: '/bulletin'
      fullPath: '/bulletin'
      preLoaderRoute: typeof BulletinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/': {
      id: '/en/'
      path: '/'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof EnRoute
    }
    '/bulletin/': {
      id: '/bulletin/'
      path: '/'
      fullPath: '/bulletin/'
      preLoaderRoute: typeof BulletinIndexRouteImport
      parentRoute: typeof BulletinRoute
    }
    '/en/sluzby': {
      id: '/en/sluzby'
      path: '/sluzby'
      fullPath: '/en/sluzby'
      preLoaderRoute: typeof EnSluzbyRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/podporujeme': {
      id: '/en/podporujeme'
      path: '/podporujeme'
      fullPath: '/en/podporujeme'
      preLoaderRoute: typeof EnPodporujemeRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/overeni-dic': {
      id: '/en/overeni-dic'
      path: '/overeni-dic'
      fullPath: '/en/overeni-dic'
      preLoaderRoute: typeof EnOvereniDicRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/odkazy': {
      id: '/en/odkazy'
      path: '/odkazy'
      fullPath: '/en/odkazy'
      preLoaderRoute: typeof EnOdkazyRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/kontakt': {
      id: '/en/kontakt'
      path: '/kontakt'
      fullPath: '/en/kontakt'
      preLoaderRoute: typeof EnKontaktRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/cenik': {
      id: '/en/cenik'
      path: '/cenik'
      fullPath: '/en/cenik'
      preLoaderRoute: typeof EnCenikRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/bulletin': {
      id: '/en/bulletin'
      path: '/bulletin'
      fullPath: '/en/bulletin'
      preLoaderRoute: typeof EnBulletinRouteImport
      parentRoute: typeof EnRoute
    }
    '/bulletin/$id': {
      id: '/bulletin/$id'
      path: '/$id'
      fullPath: '/bulletin/$id'
      preLoaderRoute: typeof BulletinIdRouteImport
      parentRoute: typeof BulletinRoute
    }
    '/en/bulletin/': {
      id: '/en/bulletin/'
      path: '/'
      fullPath: '/en/bulletin/'
      preLoaderRoute: typeof EnBulletinIndexRouteImport
      parentRoute: typeof EnBulletinRoute
    }
    '/en/bulletin/$id': {
      id: '/en/bulletin/$id'
      path: '/$id'
      fullPath: '/en/bulletin/$id'
      preLoaderRoute: typeof EnBulletinIdRouteImport
      parentRoute: typeof EnBulletinRoute
    }
  }
}

interface BulletinRouteChildren {
  BulletinIdRoute: typeof BulletinIdRoute
  BulletinIndexRoute: typeof BulletinIndexRoute
}

const BulletinRouteChildren: BulletinRouteChildren = {
  BulletinIdRoute: BulletinIdRoute,
  BulletinIndexRoute: BulletinIndexRoute,
}

const BulletinRouteWithChildren = BulletinRoute._addFileChildren(
  BulletinRouteChildren,
)

interface EnBulletinRouteChildren {
  EnBulletinIdRoute: typeof EnBulletinIdRoute
  EnBulletinIndexRoute: typeof EnBulletinIndexRoute
}

const EnBulletinRouteChildren: EnBulletinRouteChildren = {
  EnBulletinIdRoute: EnBulletinIdRoute,
  EnBulletinIndexRoute: EnBulletinIndexRoute,
}

const EnBulletinRouteWithChildren = EnBulletinRoute._addFileChildren(
  EnBulletinRouteChildren,
)

interface EnRouteChildren {
  EnBulletinRoute: typeof EnBulletinRouteWithChildren
  EnCenikRoute: typeof EnCenikRoute
  EnKontaktRoute: typeof EnKontaktRoute
  EnOdkazyRoute: typeof EnOdkazyRoute
  EnOvereniDicRoute: typeof EnOvereniDicRoute
  EnPodporujemeRoute: typeof EnPodporujemeRoute
  EnSluzbyRoute: typeof EnSluzbyRoute
  EnIndexRoute: typeof EnIndexRoute
}

const EnRouteChildren: EnRouteChildren = {
  EnBulletinRoute: EnBulletinRouteWithChildren,
  EnCenikRoute: EnCenikRoute,
  EnKontaktRoute: EnKontaktRoute,
  EnOdkazyRoute: EnOdkazyRoute,
  EnOvereniDicRoute: EnOvereniDicRoute,
  EnPodporujemeRoute: EnPodporujemeRoute,
  EnSluzbyRoute: EnSluzbyRoute,
  EnIndexRoute: EnIndexRoute,
}

const EnRouteWithChildren = EnRoute._addFileChildren(EnRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BulletinRoute: BulletinRouteWithChildren,
  CenikRoute: CenikRoute,
  EnRoute: EnRouteWithChildren,
  KontaktRoute: KontaktRoute,
  OdkazyRoute: OdkazyRoute,
  OvereniDicRoute: OvereniDicRoute,
  PodporujemeRoute: PodporujemeRoute,
  SluzbyRoute: SluzbyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
