/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SluzbyRouteImport } from './routes/sluzby'
import { Route as PodporujemeRouteImport } from './routes/podporujeme'
import { Route as OvereniDicRouteImport } from './routes/overeni-dic'
import { Route as OdkazyRouteImport } from './routes/odkazy'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as EnRouteImport } from './routes/en'
import { Route as CenikRouteImport } from './routes/cenik'
import { Route as BulletinRouteImport } from './routes/bulletin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BulletinIndexRouteImport } from './routes/bulletin.index'
import { Route as BulletinIdRouteImport } from './routes/bulletin.$id'

const SluzbyRoute = SluzbyRouteImport.update({
  id: '/sluzby',
  path: '/sluzby',
  getParentRoute: () => rootRouteImport,
} as any)
const PodporujemeRoute = PodporujemeRouteImport.update({
  id: '/podporujeme',
  path: '/podporujeme',
  getParentRoute: () => rootRouteImport,
} as any)
const OvereniDicRoute = OvereniDicRouteImport.update({
  id: '/overeni-dic',
  path: '/overeni-dic',
  getParentRoute: () => rootRouteImport,
} as any)
const OdkazyRoute = OdkazyRouteImport.update({
  id: '/odkazy',
  path: '/odkazy',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const EnRoute = EnRouteImport.update({
  id: '/en',
  path: '/en',
  getParentRoute: () => rootRouteImport,
} as any)
const CenikRoute = CenikRouteImport.update({
  id: '/cenik',
  path: '/cenik',
  getParentRoute: () => rootRouteImport,
} as any)
const BulletinRoute = BulletinRouteImport.update({
  id: '/bulletin',
  path: '/bulletin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BulletinIndexRoute = BulletinIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BulletinRoute,
} as any)
const BulletinIdRoute = BulletinIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BulletinRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bulletin': typeof BulletinRouteWithChildren
  '/cenik': typeof CenikRoute
  '/en': typeof EnRoute
  '/kontakt': typeof KontaktRoute
  '/odkazy': typeof OdkazyRoute
  '/overeni-dic': typeof OvereniDicRoute
  '/podporujeme': typeof PodporujemeRoute
  '/sluzby': typeof SluzbyRoute
  '/bulletin/$id': typeof BulletinIdRoute
  '/bulletin/': typeof BulletinIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cenik': typeof CenikRoute
  '/en': typeof EnRoute
  '/kontakt': typeof KontaktRoute
  '/odkazy': typeof OdkazyRoute
  '/overeni-dic': typeof OvereniDicRoute
  '/podporujeme': typeof PodporujemeRoute
  '/sluzby': typeof SluzbyRoute
  '/bulletin/$id': typeof BulletinIdRoute
  '/bulletin': typeof BulletinIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bulletin': typeof BulletinRouteWithChildren
  '/cenik': typeof CenikRoute
  '/en': typeof EnRoute
  '/kontakt': typeof KontaktRoute
  '/odkazy': typeof OdkazyRoute
  '/overeni-dic': typeof OvereniDicRoute
  '/podporujeme': typeof PodporujemeRoute
  '/sluzby': typeof SluzbyRoute
  '/bulletin/$id': typeof BulletinIdRoute
  '/bulletin/': typeof BulletinIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bulletin'
    | '/cenik'
    | '/en'
    | '/kontakt'
    | '/odkazy'
    | '/overeni-dic'
    | '/podporujeme'
    | '/sluzby'
    | '/bulletin/$id'
    | '/bulletin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cenik'
    | '/en'
    | '/kontakt'
    | '/odkazy'
    | '/overeni-dic'
    | '/podporujeme'
    | '/sluzby'
    | '/bulletin/$id'
    | '/bulletin'
  id:
    | '__root__'
    | '/'
    | '/bulletin'
    | '/cenik'
    | '/en'
    | '/kontakt'
    | '/odkazy'
    | '/overeni-dic'
    | '/podporujeme'
    | '/sluzby'
    | '/bulletin/$id'
    | '/bulletin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BulletinRoute: typeof BulletinRouteWithChildren
  CenikRoute: typeof CenikRoute
  EnRoute: typeof EnRoute
  KontaktRoute: typeof KontaktRoute
  OdkazyRoute: typeof OdkazyRoute
  OvereniDicRoute: typeof OvereniDicRoute
  PodporujemeRoute: typeof PodporujemeRoute
  SluzbyRoute: typeof SluzbyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sluzby': {
      id: '/sluzby'
      path: '/sluzby'
      fullPath: '/sluzby'
      preLoaderRoute: typeof SluzbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podporujeme': {
      id: '/podporujeme'
      path: '/podporujeme'
      fullPath: '/podporujeme'
      preLoaderRoute: typeof PodporujemeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overeni-dic': {
      id: '/overeni-dic'
      path: '/overeni-dic'
      fullPath: '/overeni-dic'
      preLoaderRoute: typeof OvereniDicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/odkazy': {
      id: '/odkazy'
      path: '/odkazy'
      fullPath: '/odkazy'
      preLoaderRoute: typeof OdkazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en': {
      id: '/en'
      path: '/en'
      fullPath: '/en'
      preLoaderRoute: typeof EnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cenik': {
      id: '/cenik'
      path: '/cenik'
      fullPath: '/cenik'
      preLoaderRoute: typeof CenikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulletin': {
      id: '/bulletin'
      path: '/bulletin'
      fullPath: '/bulletin'
      preLoaderRoute: typeof BulletinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulletin/': {
      id: '/bulletin/'
      path: '/'
      fullPath: '/bulletin/'
      preLoaderRoute: typeof BulletinIndexRouteImport
      parentRoute: typeof BulletinRoute
    }
    '/bulletin/$id': {
      id: '/bulletin/$id'
      path: '/$id'
      fullPath: '/bulletin/$id'
      preLoaderRoute: typeof BulletinIdRouteImport
      parentRoute: typeof BulletinRoute
    }
  }
}

interface BulletinRouteChildren {
  BulletinIdRoute: typeof BulletinIdRoute
  BulletinIndexRoute: typeof BulletinIndexRoute
}

const BulletinRouteChildren: BulletinRouteChildren = {
  BulletinIdRoute: BulletinIdRoute,
  BulletinIndexRoute: BulletinIndexRoute,
}

const BulletinRouteWithChildren = BulletinRoute._addFileChildren(
  BulletinRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BulletinRoute: BulletinRouteWithChildren,
  CenikRoute: CenikRoute,
  EnRoute: EnRoute,
  KontaktRoute: KontaktRoute,
  OdkazyRoute: OdkazyRoute,
  OvereniDicRoute: OvereniDicRoute,
  PodporujemeRoute: PodporujemeRoute,
  SluzbyRoute: SluzbyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
